skip core

diff --git a/.github/workflows/version-and-release.yml b/.github/workflows/version-and-release.yml
--- a/.github/workflows/version-and-release.yml
+++ b/.github/workflows/version-and-release.yml
@@ -33,21 +33,21 @@ jobs:
           cat <(echo -e "${{ secrets.OSSH_GPG_SECRET_KEY }}") | gpg --batch --import
           gpg --list-secret-keys --keyid-format LONG
 
-      - name: mvn versions - Core
-        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}
-        working-directory: ./core
+      # - name: mvn versions - Core
+      #   run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}
+      #   working-directory: ./core
 
-      - name: Publish - Core
-        run: |
-          mvn --no-transfer-progress \
-              --batch-mode \
-              -Dgpg.passphrase='${{ secrets.OSSH_GPG_SECRET_KEY_PASSWORD }}' \
-              -DskipTests deploy -P release
-        env:
-            MAVEN_USERNAME: ${{secrets.OSSH_USERNAME}}
-            MAVEN_PASSWORD: ${{secrets.OSSH_TOKEN}}
-        working-directory: ./core
-        continue-on-error: true  # This step will not stop the job even if it fails
+      # - name: Publish - Core
+      #   run: |
+      #     mvn --no-transfer-progress \
+      #         --batch-mode \
+      #         -Dgpg.passphrase='${{ secrets.OSSH_GPG_SECRET_KEY_PASSWORD }}' \
+      #         -DskipTests deploy -P release
+      #   env:
+      #       MAVEN_USERNAME: ${{secrets.OSSH_USERNAME}}
+      #       MAVEN_PASSWORD: ${{secrets.OSSH_TOKEN}}
+      #   working-directory: ./core
+      #   continue-on-error: true  # This step will not stop the job even if it fails
 
       - name: mvn versions - EntraID
         run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}
